---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: local-pv-lvm-values
    namespace: flux-system
    files:
      - values.yaml=local-pv-lvm-values.yaml
configurations:
  - kustomizeconfig.yaml
