apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - envoyproxy.yaml
  - gatewayclass.yaml
  - client-traffic-policy.yaml
patches:
  - path: gateway-patch.yaml
