apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - certificates.yaml
  - external-secrets-operator.yaml
  - external-secrets.yaml
  - external-dns.yaml
  # - project-contour.yaml
  - envoy-gateway.yaml
  - tailscale.yaml
  # - grafana.yaml
  # - argo-cd.yaml
  # - velero.yaml
  - cloudnative-pg.yaml
  # - retina.yaml
  # - longhorn.yaml
  # - podinfo.yaml
  - apps-bootstrap.yaml
