apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - proxyclass.yaml
  - connector-exit-node.yaml
configMapGenerator:
  - name: tailscale-values
    namespace: flux-system
    files:
      - values.yaml=tailscale-values.yaml
configurations:
  - kustomizeconfig.yaml
patches:
  - path: helmrelease.patch.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
