apiServerProxyConfig:
  mode: "true" # "true", "false", "noauth"
operatorConfig:
  hostname: understairs
  defaultTags:
    - tag:k8s-operator-understairs
  image:
    repository: ghcr.io/tailscale/k8s-operator
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
proxyConfig:
  defaultTags: tag:k8s-understairs
  defaultProxyClass: control-plane
  image:
    repository: ghcr.io/tailscale/tailscale
