apiServerProxyConfig:
  mode: "true" # "true", "false", "noauth"
operatorConfig:
  hostname: freeloader
  image:
    repository: ghcr.io/tailscale/k8s-operator
proxyConfig:
  image:
    repository: ghcr.io/tailscale/tailscale
