apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - lb-ippool.yaml
  - l2-announcement.yaml
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    behavior: merge
    files:
      - values.yaml=cilium-values.yaml
