---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - storageclass.yaml
configMapGenerator:
  - name: openebs-localpv-values
    namespace: flux-system
    files:
      - values.yaml=openebs-localpv-values.yaml
configurations:
  - kustomizeconfig.yaml
patches:
  - target:
      kind: StorageClass
      name: openebs-lvm
    patch: |
      $patch: delete
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: openebs-lvm
