apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - tailscale.yaml
  - tailscale-config.yaml
  - cert-manager.yaml
  - certificates.yaml
  # - envoy-gateway.yaml
  # - envoy-gateway-config.yaml
  - external-secrets.yaml
